package leetcodeproblems.stringproblems;

public class FindTheDifference {
    public static void main(String[] args) {
        System.out.println(findTheDifference("abcd","abcde"));
    }
    /**
     * @Important
     * @XOR OPERATION
     * @Leetcode
     * @389. Find the Difference
     * @https://leetcode.com/problems/find-the-difference/description/
     * You are given two strings s and t.
     *
     * String t is generated by random shuffling string s and then add one more letter at a random position.
     *
     * Return the letter that was added to t.
     *
     * Example 1:
     *
     * Input: s = "abcd", t = "abcde"
     * Output: "e"
     * Explanation: 'e' is the letter that was added.
     * Example 2:
     *
     * Input: s = "", t = "y"
     * Output: "y"
     * */
    public static char findTheDifference(String s, String t) {
        char result = 0;
        for(char s1 : s.toCharArray())
            result = (char) (result ^ s1);
        for(char t1 : t.toCharArray())
            result = (char) (result ^ t1);
        return result;
    }
}
